config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :edit, :show, :index, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :favourites, only: [:index, :create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favourites, dependent: :destroy
  has_many :favourite_users, through: :favourites, source: :user
  validates :content, presence: true, length: {maximum: 255}
  validates :image, presence:true
  mount_uploader :image, ImageUploader
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  has_many :favourites, dependent: :destroy
  has_many :favourite_blogs, through: :favourites, source: :blog
  validates :name ,presence: true, length: {maximum: 50}
  validates :email ,presence: true, length: {maximum: 255},format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, on: :create
  before_validation {email.downcase!}
  has_secure_password
  validates :password ,presence: true, length: {minimum: 8}, on: :create
  validates :image, presence:true
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :show, :update, :destroy]
  def index
    @blogs = Blog.all
  end
  def new
    @blog = Blog.new
  end
  def create
    if params[:back]
      @blog = current_user.blogs.build(blog_params)
      render :new
    else
      @blog = current_user.blogs.build(blog_params)
      if @blog.save
        ContactMailer.contact_mail(@blog).deliver
        redirect_to blogs_path, notice: "Post created"
      else
        render :new
      end
    end
  end
  def edit
  end
  def show
    @favourite = current_user.favourites.find_by(blog_id: @blog.id)
  end
  def update
    if current_user && current_user.id == @blog.user_id
      if @blog.update(blog_params)
        redirect_to blogs_path, notice: "Post updated"
      else
        render :edit
      end
    else
      render :edit
    end
  end
  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end
  def destroy
    if current_user && current_user.id == @blog.user_id
      @blog.destroy
      redirect_to blogs_path, notict: "Post deleted"
    else
      render :new
    end
  end
  private
  def set_blog
    @blog = Blog.find(params[:id])
  end
  def blog_params
    params.require(:blog).permit(:content, :image, :image_cache)
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @favourites = current_user.favourites
  end
  def create
    favourite = current_user.favourites.create(blog_id: params[:blog_id])
    redirect_to blogs_path, notice: "Liked"
  end
  def destroy
    current_user.favourites.find_by(id: params[:id]).destroy
    redirect_to blogs_path, notice: "Unliked"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end
  def create
    user=User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id]=user.id
      redirect_to blogs_path
    else
      flash.now[:danger]="Login Fail"
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice]="Logged out"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def edit
  end
  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  def show
  end
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create' || action_name == 'confirm'
      confirm_blogs_path
    else action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||=User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/views/blogs/_form.html.erb
<div class="blog_div">
  <%= form_with(model: @blog, local: true, url: choose_new_or_edit) do |f| %>
    <%= f.text_field :content, placeholder:"Type here", class:"new_post" %>
    <%= f.file_field :image , class:"new_post"%>
    <%= image_tag(@blog.image.url, class:"image_style") if @blog.image && @blog.image.url %>
    <%= f.hidden_field :image_cache %>
    <%= f.submit 'Post', class:"post_btn"%>
  <% end %>
</div>

app/views/blogs/confirm.html.erb
<div class="blog_div" align="center">
  <%= form_with(model: @blog, local: true, url: blogs_path) do |f| %>
    <%= f.hidden_field :content %><br>
    <%= f.hidden_field :image %><br>
    <p class="new_post"><%= @blog.content %></p>
    <%= image_tag(@blog.image.url, class:"image_style") if @blog.image && @blog.image.url %>
    <%= f.hidden_field :image_cache %><br>
    <%= f.submit 'Post', class:"create_btn"%>
    <%= f.submit 'Back', name: 'back', class:"back_btn"%>
  <% end %>
</div>

app/views/blogs/edit.html.erb
<h2 align="center">
<span class="glyphicon glyphicon-erase"></span></h2>
<%= render 'form'%>

app/views/blogs/index.html.erb
<div class="home_div">
  <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16" id="home_icon">
    <path fill-rule="evenodd" d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
    <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
  </svg>
  <%= link_to new_blog_path, class:"create_post_btn" do %>
  <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-plus-square-fill" viewBox="0 0 16 16">
    <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z"/>
  </svg>
  <% end %>
  <% @blogs.each do |b| %>
  <div class="blog_div">
    <%= image_tag b.user.image.url, class: "profile_image"%>
    <p class="user_name"><%= b.user.name %></p><br>
    <%= image_tag b.image.url, class:"image_style" %><br>
    <p style="white-space:pre-wrap"><%= b.content %></p><br>
    <% if current_user && current_user.id == b.user_id %>
      <div class="links_div" >
        <%= link_to edit_user_path(b.user.id), class:"links" do%>
          <span class="glyphicon glyphicon-user"></span>
        <% end %>
        <%= link_to edit_blog_path(b.id), data: {confirm: "Confirm Edit!"}, class:"links" do%>
          <span class="glyphicon glyphicon-erase"></span>
        <% end %>
        <%= link_to blog_path(b.id), method: :delete, data: {confirm: "Confirm Delete!"} , class:"links" do%>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
  <% end %>
        <%= link_to blog_path(b.id), class:"links" do%>
          <span class="glyphicon glyphicon-eye-open"></span>
        <% end %>
      </div>
  </div>
  <% end %>
</div>

app/views/blogs/new.html.erb
<h2 align="center">
  <span class="glyphicon glyphicon-pencil"></span>
</h2>
<%= render 'form'%>

app/views/blogs/show.html.erb
<h2 align="center">
  <span class="glyphicon glyphicon-picture"></span>
</h2>
<div class="blog_div">
  <p class="user_name"><%= @blog.user.name %></p><br>
  <p class="new_post"><%= @blog.content %></p><br>
  <%= image_tag @blog.image.url, class:"image_style" %><br>
    <% if @favourite.present? %>
      <%= link_to favourite_path(id: @favourite.id), method: :delete, class:"favourite_icon" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-emoji-frown-fill" viewBox="0 0 16 16">
          <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm-2.715 5.933a.5.5 0 0 1-.183-.683A4.498 4.498 0 0 1 8 9.5a4.5 4.5 0 0 1 3.898 2.25.5.5 0 0 1-.866.5A3.498 3.498 0 0 0 8 10.5a3.498 3.498 0 0 0-3.032 1.75.5.5 0 0 1-.683.183zM10 8c-.552 0-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5S10.552 8 10 8z"/>
        </svg>
      <% end %>
    <% else %>
      <%= link_to favourites_path(blog_id: @blog.id), method: :post, class:"favourite_icon" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-emoji-smile-fill" viewBox="0 0 16 16">
          <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zM4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683zM10 8c-.552 0-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5S10.552 8 10 8z"/>
        </svg>
      <% end %>
    <% end %>
      <%= link_to new_blog_path, class:"create_post_btn" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-square-fill" viewBox="0 0 16 16">
          <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z"/>
        </svg>
      <% end %>
<% if current_user && current_user.id == @blog.user_id %>
  <%= link_to edit_blog_path(@blog.id), data: {confirm: "Confirm Edit!"}, class:"eraser_icon" do %>
    <span class="glyphicon glyphicon-erase"></span>
  <% end %>
<% end %>
</div>

app/views/favourites/index.html.erb
<h2 align="center">
  <span class="glyphicon glyphicon-heart"></span>
</h2>
<% @favourites.each do |favourite| %>
  <div class="blog_div">
    <p style="white-space:pre-wrap"><%= favourite.blog.content %></p>
    <%= image_tag favourite.blog.image.url, class:"image_style" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=divice-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div align="center">
      <% flash.each do |key,value|%>
        <%= content_tag(:div,value,class:"#{key}") %><br>
      <% end %>
      <% if logged_in? %>
        <%= link_to "Logout |", session_path(current_user.id), method: :delete, class:"top_links"%>
        <%= link_to "Create Account |", new_user_path, class:"top_links"%>
        <%= link_to 'Home |', blogs_path , class:"top_links"%>
        <%= link_to "Favourites", favourites_path , class:"top_links"%>
      <% else %>
        <%= link_to "Log In |", new_session_path, class:"top_links"%>
        <%= link_to "Create Account", new_user_path, class:"top_links"%>
      <% end %>
    </div>
    <h1>InstaClone</h1>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h2 align="center">
<span class="glyphicon glyphicon-user"></span></h2>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error")%></h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="blog_div">
<%= form_with(model: @user, local: true, url: user_path) do |f| %>
  <%= f.text_field :name, placeholder: "Name", class:"new_post" %><br>
  <%= f.file_field :image, class:"new_post" %><br>
  <%= f.submit "Update Account", class:"post_btn" %>
  <%= link_to 'Home', blogs_path , class:"post_btn"%>
<% end %>
</div>

app/views/users/new.html.erb
<h2 align="center">Create Account</h2>
<% if @user.errors.any? %>
  <div id="error_explanation" class="blog_error">
    <h3 align="center"><%= pluralize(@user.errors.count, "error")%></h3>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>
  </div>
<div class="blog_div">
  <%= form_with(model: @user, local: true, url: users_path) do |f| %>
    <%= f.text_field :name, placeholder: "Name", class:"new_post"%><br>
    <%= f.text_field :email, placeholder: "Email", class:"new_post"%><br>
    <%= f.password_field :password, placeholder: "Password", class:"new_post"%><br>
    <%= f.password_field :password_confirmation, placeholder: "Password Confirmation", class:"new_post"%><br>
    <%= f.file_field :image, class:"new_post"%><br>
    <%= f.submit "Create Account", class:"post_btn" %>
    <% end %>
</div>

app/views/users/show.html.erb
<h2 align="center">
<span class="glyphicon glyphicon-user"></span></h2>
<div class="blog_div">
  <p class="user_name"><%= @user.name %></p><br>
  <%= image_tag @user.image.url, class:"image_style"%><br>
  <%= link_to 'Edit Profile', edit_user_path , class:"post_btn"%>
  <%= link_to 'Home', blogs_path , class:"post_btn"%>
</div>